### ISSUE TITLE
"Anita has stopped working"

### ISSUE THREAD

**Issue by MeIsAnonymous** [SachsenCoder/Anita#13]
I'm not a very good coder, but when i try to use Anita it works fine until i hit the fetch button. As soon as i do that, the program crashes and a window popups saying: "Anita has stopped working", when i close the popup the program closes. So i'm not able to actually download any pictures. I'm on windows 8, don't know if that is the problem? Although i tried setting the compatability settings to windows 7 but that didn't work... Would be awesome if this bug was fixed :) I love the idea and i've actually been for this exact program for long time, and now i've found it! :) So i would be so happy if i could start using it! :)
I took a screenshot. It's swedish but it says: Anita has stopped working
[pic](https://cloud.githubusercontent.com/assets/10471608/5690219/9402ca4a-987b-11e4-80fc-25fde37db7be.png)

**Comment by SachsenCoder** [comment]
Thank you for the information!
It's a long time ago, since I used or worked on the software. I tested it now and the same error happens at me.
Windows 8 is ok and that's not the problem. I will check out the problem with the debugger. I'm sure, there changed some things on the target website, which result to that error. Stay tuned, I will try to fix it as fast as possible! :-)

**Comment by SachsenCoder** [comment]
OK, the problem is more complicated, because it seems, that the wikifeet html markup is now much more worse, so that the current parser library can not handle it properly. I have to replace the parser by a more error tolerant one and hope, that it will work then again.
Nevertheless, there have also changed some things on the website itself, which have to be fixed.

Overall, it will take a bit longer to fix that stuff.

**Comment by MeIsAnonymous** [comment]
Ok, thanks for taking the time and replying this fast! Keep up the awesome work! :)

**Comment by SachsenCoder** [comment]
OK, the new working release is here: https://github.com/SachsenCoder/Anita/releases/tag/R1.5
Just replace the old files with the new ones and ... happy downloading again! :-D

**Comment by MeIsAnonymous** [comment]
Thank you so much! It works! :)

**Comment by chibifibi** [comment]
Hi, SaschenCoder. Today is the first day I am using your software and the first time I use github, so I might be asking in the wrong place but; I am running on Windows 7 and the program crashes when I click on Fetch Data. It says "Anita has stopped working". Maybe the website has changed again?

**Comment by SachsenCoder** [comment]
Yeah, it seems, there is something strange again. I will check this out and fix it soon. But not today, because I'm too tired.
Yes, I'm sure there changed something again on that website.

**Comment by SachsenCoder** [comment]
OK, the error is fixed again. ;-)
It was just a small thing. The new release is here: https://github.com/SachsenCoder/Anita/releases/tag/R1.6

**Comment by chibifibi** [comment]
Man, you're my hero.

**Comment by prophecii** [comment]
for some reason its not working, im using windows 7 i type in the name and select where to download to and just pops up anita has stopped working

**Comment by SachsenCoder** [comment]
I will check this, when I'm in the mood and find some time. :-)
